name: Setup Runner Environment (No Docker)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-env:
    name: Installer l'environnement IA (NetSecurePro)
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Mettre à jour le système
        run: sudo apt update && sudo apt upgrade -y

      - name: Installer Python et les dépendances
        run: |
          sudo apt install -y python3 python3-pip
          pip3 install --upgrade pip
          pip3 install -r requirements.txt

      - name: Vérification des versions
        run: |
          python3 --version
          pip3 --version
